### PR TITLE
Implement CorsViewMixin

### LINKED ISSUE #41: Class based views are not supported
When using web.View as the handler if the route being added for '*' then cors doesn't work because the server seems not to be able to find the OPTIONS. Not sure why that is, I didn't take the time to investigate but my guess is that the \* end up taking priority and the routing goes to the \* handler instead of the CORS handler.

### PR DESCRIPTION
**Pull request by pedrokiefer**
Fix #41!

### CODE REVIEW

**Comment by evandroeisinger** [comment]
Great contribution!

**Comment by asvetlov** [comment]
@pedrokiefer please take a look on https://codecov.io/gh/aio-libs/aiohttp-cors/pull/145/diff
Or install [codecov browser extension](https://docs.codecov.io/v4.3.6/docs/browser-extension) to see test coverage just in github diff tab. 
Yellow and red lines should be covered.

**Comment by asvetlov** [comment]
P.S. I like the PR in general, usage snippet looks pretty elegant.

**Comment by pedrokiefer** [comment]
@asvetlov thanks, i'll work on those issues tomorrow.

**Comment by asvetlov** [comment]
I see many duplications (copy-pastes from `cors_config.py`).
Would you refactor the code to avoid it?

**Comment by pedrokiefer** [comment]
My first try was reusing `cors_config.py` methods, and it failed miserably. Now that I've got a working version, with tests in place, might be easier to get it right.

Do you have any objection on extracting `_preflight_handler`, `_parse_request_headers` and `_parse_request_method` to another class, and composing both the mixin and `_CorsConfigImpl` ?

**Comment by asvetlov** [comment]
> Do you have any objection on extracting `_preflight_handler`, `_parse_request_headers` and `_parse_request_method` to another class, and composing both the mixin and `_CorsConfigImpl`

Love the idea. Especially love underscore prefix for proposed names :)

**Comment by pedrokiefer** [comment]
Done! :)

**Comment by asvetlov** [comment]
Cool!
Let me make a final review and merge tomorrow.

**Comment by asvetlov** [comment]
Thanks!
Initiated 0.6.0 release

**Pull request merged**
